# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1080, 720)
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ironManBack = QtWidgets.QLabel(Widget)
        self.ironManBack.setGeometry(QtCore.QRect(680, -20, 541, 721))
        self.ironManBack.setText("")
        self.ironManBack.setPixmap(QtGui.QPixmap("E:\\CODING\\Artificial_Intelligence\\Ultimate JARVIS with GUI YT  Playlist files\\gui_tools\\ironman-portrait.webp"))
        self.ironManBack.setScaledContents(True)
        self.ironManBack.setObjectName("ironManBack")
        self.kartisTechLabel = QtWidgets.QLabel(Widget)
        self.kartisTechLabel.setGeometry(QtCore.QRect(120, 10, 811, 101))
        self.kartisTechLabel.setStyleSheet("background-color: transparent;")
        self.kartisTechLabel.setText("")
        self.kartisTechLabel.setPixmap(QtGui.QPixmap("E:\\CODING\\Artificial_Intelligence\\Ultimate JARVIS with GUI YT  Playlist files\\gui_tools\\KartisTechnology(white).png"))
        self.kartisTechLabel.setScaledContents(True)
        self.kartisTechLabel.setObjectName("kartisTechLabel")
        self.videoBack = QtWidgets.QLabel(Widget)
        self.videoBack.setGeometry(QtCore.QRect(20, 110, 681, 491))
        self.videoBack.setStyleSheet("border-color: rgb(255, 255, 255);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border-style:solid;\n"
                                   "border-width: 1px 1px 1px 1px;")
        self.videoBack.setText("")
        self.videoBack.setObjectName("videoBack")
        self.loginButton = QtWidgets.QPushButton(Widget)
        self.loginButton.setGeometry(QtCore.QRect(20, 620, 221, 81))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/login with border.png);\n"
                                      "background-color: transparent;")
        self.loginButton.setText("")
        self.loginButton.setObjectName("loginButton")
        self.exitButton = QtWidgets.QPushButton(Widget)
        self.exitButton.setGeometry(QtCore.QRect(280, 620, 221, 81))
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/exit(with border).png);\n"
                                        "background-color: transparent;")
        self.exitButton.setText("")
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
