# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindowClass(object):
    def setupUi(self, loginWindowClass):
        loginWindowClass.setObjectName("loginWindowClass")
        loginWindowClass.resize(1080, 720)
        loginWindowClass.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.kartisLabel = QtWidgets.QLabel(loginWindowClass)
        self.kartisLabel.setGeometry(QtCore.QRect(179, 10, 691, 81))
        self.kartisLabel.setText("")
        self.kartisLabel.setPixmap(QtGui.QPixmap("E:\\CODING\\Artificial_Intelligence\\Ultimate JARVIS with GUI YT  Playlist files\\gui_tools\\KartisTechnology(white).png"))
        self.kartisLabel.setScaledContents(True)
        self.kartisLabel.setObjectName("kartisLabel")
        self.mainFrame = QtWidgets.QFrame(loginWindowClass)
        self.mainFrame.setGeometry(QtCore.QRect(179, 119, 691, 591))
        self.mainFrame.setStyleSheet("color: rgb(255, 255, 255);\n"
                                     "border-color: rgb(255, 255, 255);\n"
                                     "border-radius: 30px;\n"
                                     "border-width:5px 5px 5px 5px;\n"
                                     "border-style: solid;")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.retryButton = QtWidgets.QPushButton(self.mainFrame)
        self.retryButton.setGeometry(QtCore.QRect(40, 490, 191, 81))
        self.retryButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/retry.png);\n"
                                       "background-color: transparent;")
        self.retryButton.setText("")
        self.retryButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.retryButton.setObjectName("retryButton")
        self.backButton = QtWidgets.QPushButton(self.mainFrame)
        self.backButton.setGeometry(QtCore.QRect(250, 488, 191, 81))
        self.backButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/back.png);\n"
                                      "background-color: transparent;")
        self.backButton.setText("")
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setObjectName("backButton")
        self.exitButton = QtWidgets.QPushButton(self.mainFrame)
        self.exitButton.setGeometry(QtCore.QRect(460, 490, 191, 81))
        self.exitButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/exit.png);\n"
                                      "background-color: transparent;")
        self.exitButton.setText("")
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setObjectName("exitButton")
        self.usernameEntry = QtWidgets.QLineEdit(self.mainFrame)
        self.usernameEntry.setGeometry(QtCore.QRect(130, 140, 391, 81))
        self.usernameEntry.setStyleSheet("font: 30pt \"IRON MAN OF WAR 2 NCV\";\n"
                                         "padding-left:10px;")
        self.usernameEntry.setObjectName("usernameEntry")
        self.passwordEntry = QtWidgets.QLineEdit(self.mainFrame)
        self.passwordEntry.setGeometry(QtCore.QRect(130, 250, 391, 81))
        self.passwordEntry.setStyleSheet("font: 30pt \"IRON MAN OF WAR 2 NCV\";\n"
                                         "padding-left:10px;")
        self.passwordEntry.setObjectName("passwordEntry")
        self.loginButton = QtWidgets.QPushButton(self.mainFrame)
        self.loginButton.setGeometry(QtCore.QRect(221, 340, 221, 71))
        self.loginButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/login-empty.png);\n"
                                       "background-color: transparent;")
        self.loginButton.setText("")
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setObjectName("loginButton")
        self.illegalEntry = QtWidgets.QLabel(self.mainFrame)
        self.illegalEntry.setGeometry(QtCore.QRect(120, 80, 431, 351))
        self.illegalEntry.setStyleSheet("border: none;")
        self.illegalEntry.setText("")
        self.illegalEntry.setPixmap(QtGui.QPixmap("E:\\CODING\\Artificial_Intelligence\\Ultimate JARVIS with GUI YT  Playlist files\\illegalEntry.gif"))
        self.illegalEntry.setScaledContents(True)
        self.illegalEntry.setObjectName("illegalEntry")

        self.retranslateUi(loginWindowClass)
        QtCore.QMetaObject.connectSlotsByName(loginWindowClass)

    def retranslateUi(self, loginWindowClass):
        _translate = QtCore.QCoreApplication.translate
        loginWindowClass.setWindowTitle(_translate("loginWindowClass", "loginWindowClass"))
        self.usernameEntry.setPlaceholderText(_translate("loginWindowClass", "USERNAME"))
        self.passwordEntry.setPlaceholderText(_translate("loginWindowClass", "PASSWORD"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    loginWindowClass = QtWidgets.QWidget()
    ui = Ui_loginWindowClass()
    ui.setupUi(loginWindowClass)
    loginWindowClass.show()
    sys.exit(app.exec_())
