# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 550)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.kartistech = QtWidgets.QLabel(Dialog)
        self.kartistech.setGeometry(QtCore.QRect(0, 10, 691, 91))
        self.kartistech.setStyleSheet("background-color: transparent;")
        self.kartistech.setText("")
        self.kartistech.setPixmap(QtGui.QPixmap("E:\\CODING\\Artificial_Intelligence\\Ultimate JARVIS with GUI YT  Playlist files\\gui_tools\\KartisTechnology(white).png"))
        self.kartistech.setScaledContents(True)
        self.kartistech.setObjectName("kartistech")
        self.mainGIF = QtWidgets.QLabel(Dialog)
        self.mainGIF.setGeometry(QtCore.QRect(10, 80, 681, 381))
        self.mainGIF.setText("")
        self.mainGIF.setPixmap(QtGui.QPixmap("E:\\CODING\\Artificial_Intelligence\\Ultimate JARVIS with GUI YT  Playlist files\\gui_tools\\Jarvis_Gui (2).gif"))
        self.mainGIF.setScaledContents(True)
        self.mainGIF.setObjectName("mainGIF")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(30, 472, 201, 71))
        self.startButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/start.png);\n"
                                       "background-color: transparent;background-color: transparent;")
        self.startButton.setText("")
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setObjectName("startButton")
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setGeometry(QtCore.QRect(240, 470, 201, 71))
        self.loginButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/login.png);\n"
                                       "background-color: transparent;background-color: transparent;")
        self.loginButton.setText("")
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setObjectName("loginButton")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(490, 470, 201, 71))
        self.exitButton.setStyleSheet("border-image: url(E:/CODING/Artificial_Intelligence/Ultimate JARVIS with GUI YT  Playlist files/gui_tools/exit.png);\n"
                                      "background-color: transparent;background-color: transparent;")
        self.exitButton.setText("")
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
